baseurl: /brussels
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: brussels
github_org: maptime
maptime:
  chapter: MaptimeBrussels
  #twitter: TwitterHandle
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
