baseurl: /belgium
permalink: pretty
future: true
markdown: kramdown
paginate: 5
repo: belgium
github_org: maptime
maptime:
  chapter: Maptime Belgium
  twitter: osm_be
  #disqus: YOUR DISQUS USERNAME

gems:
  - jekyll-feed
